# Generated by Django 5.0.3 on 2024-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_booking_created_by_booking_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(related_name='bookings', to='hotel_app.room'),
        ),
    ]
