# Generated by Django 5.0.3 on 2024-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_remove_booking_room_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='rooms',
        ),
    ]
