# Generated by Django 5.0.3 on 2024-10-02 06:27

import django.core.validators
import hotel_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_rename_room_booking_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(validators=[hotel_app.models.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[hotel_app.models.validate_salary]),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')]),
        ),
    ]
