# Generated by Django 5.0.3 on 2024-10-02 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Room Number must contain only digits.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Room Number must contain only digits.', regex='^[0-9]+$')]),
        ),
    ]
