# Generated by Django 5.0.3 on 2024-10-02 09:32

import django.core.validators
import hotel_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_alter_room_price_per_night_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[hotel_app.models.validate_price_per_night]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_room_number', message='Room Number must contain only digits.', regex='^[0-9]+$')]),
        ),
    ]
