# Generated by Django 5.0.3 on 2024-10-02 15:45

import django.core.validators
import django.utils.timezone
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_alter_room_capacity_alter_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[utils.validators.validate_total_price]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only alphabets and single spaces between words.', regex='^[A-Za-z]+( [A-Za-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Position must contain only alphabetic or alphanumeric characters, but not only numbers.', regex='^(?!^\\d+$)[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Address must not contain the dollar sign ($) or dot (.).', regex='^[^$.]+$')]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(validators=[utils.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='passport',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Passport must contain only numbers and dashes (-).', regex='^[0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[utils.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
