# Generated by Django 5.0.3 on 2024-10-03 12:32

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_alter_booking_total_price_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/', validators=[utils.validators.validate_image]),
        ),
    ]
