# Generated by Django 5.0.3 on 2024-10-10 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_input', message='This field accepts only alphabetic characters and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Position must contain only alphabetic or alphanumeric characters, but not only numbers.', regex='^(?!^\\d+$)[a-zA-Z0-9 ]+$')]),
        ),
    ]
