# Generated by Django 5.0.3 on 2024-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_alter_employee_department_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
