# Generated by Django 5.0.3 on 2024-10-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_booking_adults_booking_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id']},
        ),
    ]
