# Generated by Django 5.0.3 on 2024-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_user_cnic_remove_user_current_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
